#!/www/server/mdserver-web/bin/python
# description: mdserver-web cli tools
# ln -s /www/server/mdserver-web/mw-cli /usr/bin/mw-cli
import os
import sys


def mw_start():
    """
    Start mdserver-web
    """
    os.system('systemctl start mw')
    print("服务已启动")


def mw_stop():
    """
    stop mdserver-web
    """
    os.system('systemctl stop mw')
    print("服务已停止")


def mw_restart():
    """
    restart mdserver-web
    """
    os.system('systemctl restart mw')
    print("服务已重启")


def mw_reset_username():
    """
    reset mdserver-web username
    """
    from tools import set_panel_username
    user_name = input("请输入新的用户名: ")
    set_panel_username(user_name)


def mw_reset_pwd():
    """
    reset mdserver-web password
    """
    from tools import set_panel_pwd
    pwd = input("请输入新的密码: ")
    set_panel_pwd(pwd, True)


if __name__ == '__main__':
    os.chdir("/www/server/mdserver-web")
    sys.path.append(os.getcwd() + "/class/core")

    try:
        str = '''
        ====  mdserver-web cli tools ====
        1. 启动服务    2. 停止服务
        3. 重启服务    4. 修改用户名
        5. 修改密码
        =================================
        '''
        if len(sys.argv) == 2:
            sw = sys.argv[1]
        else:
            print(str)
            sw = input("请输入您要进行的操作: ")

        if sw == '1':
            mw_start()
        elif sw == '2':
            mw_stop()
        elif sw == '3':
            mw_restart()
        elif sw == '4':
            mw_reset_username()
        elif sw == '5':
            mw_reset_pwd()
        else:
            print("操作不存在")
    except KeyboardInterrupt:
        print("\n操作已终止")
